### ISSUE TITLE
Feed playback not working as expected

### ISSUE THREAD

**Issue by oliver-lehner** [AFlowOfCode/bandcamp-streamer#4]
I've been using the extension to listen through my feed and it always served this purpose well. Now I have a problem: when I scroll ahead in my feed and click on an item to play the featured track, the extension would always play some featured track higher up in the feed. So I can't select a starting point for continuous playback and sadly this has rendered the extension unusable for me. Sometimes I have to catch up on weeks of releases and I can't be bothered to navigate this many items using the Next Button in the extension. 

Thank you though for making continuous playback (something that should be built into bandcamp anyway) at least for some time possible and let me know if I can further assist in troubleshooting this issue. I am fairly sure the described behaviour didn't cause problems in the past.

I am using FF 95.0.2

**Comment by AFlowOfCode** [comment]
Hi, as I cannot reproduce this myself, I think it may be related to a specific track that is in your feed. Sometimes there are certain types of releases / tracks that can mess things up - for example, subscriber-only or featured tracks that were later removed by the artist. I've tried to fix every instance of this I have seen so nothing gets jumbled, but maybe I have not seen them all. 

I am pretty sure you're talking about items in the left column "fan activity" list and not the "new releases" list right? Correct me if I'm wrong.

Can you help me try to figure it out by following these steps? 

1. Freshly load your feed & don't load any extra tracks. Play a track item below the first track. If it messes up go to step 3, otherwise go to step 2.

2. If it plays like normal, scroll to the bottom of the page to load more tracks & press play on one from the new set. If it still doesn't bug out reload the page, load more tracks before playing anything, then press play on one of the new ones. Basically try to find the shortest number of steps that leads you to the problem.

3. Open the console tab in the FF devtools, click somewhere on the messages & press ctrl+a to select all (or select it all manually).

4. Save all that to a text file & upload as attachment to a response here. You can email it to me if you don't want anyone to see your Bandcamp username as that will be in the log somewhere. 

Thanks!

**Comment by AFlowOfCode** [comment]
Actually that won't be necessary. I found & fixed an issue with tracks that appear in the feed multiple times which led to this behavior. 

I'm currently finishing up a couple features (search result playlists & loading entire collections/wishlists at one time) & should have a new release available very soon. I'll post here once it's released on FF to give you a chance to confirm the issue is fixed.

**Comment by oliver-lehner** [comment]
Hi, thanks for looking into it. I've checked a little bit more thoroughly how to reproduce the error. Yes, it happens in Fan Activity and it happens after I hit a certain page in my feed. I've attached the [console output.](https://github.com/AFlowOfCode/bandcamp-streamer/files/7858463/bandcamp-error-log.txt)
 
I followed your steps and repeatedly scrolled to fetch batches of tracks a few more times. Playback will fail always at the first item on one specific page and will cue a track from higher up in the feed (in my console output the first track that won't play is "Mosh Pit feat. DJ Ph")

I hope this confirms your observation that tracks appearing multiple times is the issue.

**Comment by AFlowOfCode** [comment]
It does indeed. Duplicates were knocking the art out of sync down the line since the actual playlist ended up shorter than the number of items shown in the feed. However the duplicate tracks are supposed to appear as many times as they naturally occur in the feed, which is what is happening now. From my testing I believe it's all set, but let me know if you come across any issues.

The update should be live on FF as of now & will automatically update to v1.3 if you have auto-updating set. Chrome usually takes longer so that will hopefully be live within a week.

**Comment by oliver-lehner** [comment]
Unfortunately the issue persists with v1.3. I [attached](https://github.com/AFlowOfCode/bandcamp-streamer/files/7878051/bandcamp-error-log-v1.3.0.txt) the most recent console output. It happens at the beginning of page 5 of the feed. Instead of playing the first track of the new batch, the extension plays the very first track from the top.

**Comment by AFlowOfCode** [comment]
Interesting, this actually seems to be a problem that could have in theory arisen at any point depending on the arrangement of tracks in the feed.

I patched it so I hope version 1.3.1 will work for you, should be up now. Thanks for the log as it would have been very difficult to figure out what happened otherwise.
